### ISSUE TITLE
R word command url returns 404

### ISSUE THREAD

**Issue by hippyclipper** [nclgbd/Little-Amber#14]
![image](https://user-images.githubusercontent.com/79437955/124700825-4a723900-dea2-11eb-83a1-89e2e522160b.png)

**Comment by nclgbd** [comment]
Oh well.... shit. I'll fix this soon 😄

**Comment by nclgbd** [comment]
Should be fixed now~

https://github.com/nclgbd/Little-Amber/pull/16#issuecomment-875441109
